# Site Settings

disqus:              true

paginate:            1

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:                [jekyll-paginate]
