title:  "FN3142"
description:
author:
  name: "pardhu448"
  twitter: 

menu:
- {name: 'Lectures', file: 'lectures.html'}
- {name: 'Exams', file: 'exam.html'}
- {name: 'Resources', file: 'resources.html'}
- {name: 'Software', file: 'software.html'}
- {name: 'Contact', file: 'about.html'}

social:
- {icon: 'facebook', link: 'https://www.facebook.com'}
- {icon: 'linkedin', link: 'https://linkedin.com'}

homegriditems:
- {title: 'Lectures', file: 'lectures.html', mintitle: '', prose: 'Complete list of lectures slides and notes.'}
- {title: 'Announcements', file: 'announcements.html', mintitle: 'Homework', prose: 'Weekly tasks and homework assignments.'}
- {title : 'Software', file: 'software.html', mintitle: 'Using data', prose: 'Resources for Python installation and mini-projects.'}
- {title : 'Resources', file: 'resources.html', mintitle: 'Other', prose: 'Links to other relevant resources on web.'}

jsarr:
- {name : 'slideshow_script', file: 'slide_java.js'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
